#!/usr/bin/env python3
"""Create a markdown summary for a local research_ops iteration."""

from __future__ import annotations

import argparse
from pathlib import Path


FILES = [
    "00_request.md",
    "01_cartography.md",
    "02_rfc.md",
    "03_implementation_summary.md",
    "04_verifier_report.md",
    "05_decision_memo.md",
]


def clean_yaml_value(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == '"':
        value = value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return value


def read_yamlish(path: Path) -> dict[str, object]:
    data: dict[str, object] = {}
    current_key = ""
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("- "):
            if current_key:
                data.setdefault(current_key, [])
                if isinstance(data[current_key], list):
                    data[current_key].append(clean_yaml_value(stripped[2:]))
            continue
        if ":" not in stripped:
            continue
        key, value = stripped.split(":", 1)
        key = key.strip()
        value = value.strip()
        if value:
            data[key] = clean_yaml_value(value)
            current_key = ""
        else:
            data[key] = []
            current_key = key
    return data


def resolve_iteration(root: Path, value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    direct = root / value
    by_id = root / "research_ops" / "iterations" / value
    return direct if direct.exists() else by_id


def build_summary(iteration_dir: Path, manifest: dict[str, object]) -> str:
    lines = [
        "# Iteration Summary",
        "",
        f"Iteration: `{manifest.get('iteration_id', iteration_dir.name)}`",
        f"Assumption: `{manifest.get('assumption_id', 'unknown')}`",
        f"Title: {manifest.get('title', '')}",
        f"Status: `{manifest.get('status', 'unknown')}`",
        f"Created: `{manifest.get('created_at', 'unknown')}`",
        "",
        "## File Status",
        "",
        "| File | Exists |",
        "|---|---:|",
    ]
    for filename in FILES:
        lines.append(f"| `{filename}` | {str((iteration_dir / filename).exists()).lower()} |")
    lines.extend(["", "## Notes", "", "- Generated by `research_ops/scripts/summarize_iteration.py`."])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("iteration", help="iteration directory or iteration id")
    parser.add_argument("--root", default=None, help="repository root; defaults to cwd")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing artifacts/iteration_summary.md")
    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve() if args.root else Path.cwd().resolve()
    iteration_dir = resolve_iteration(root, args.iteration)
    manifest = read_yamlish(iteration_dir / "manifest.yaml")
    summary = build_summary(iteration_dir, manifest)
    if args.stdout:
        print(summary, end="")
    else:
        path = iteration_dir / "artifacts" / "iteration_summary.md"
        path.write_text(summary, encoding="utf-8")
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
