#!/usr/bin/env python3
"""Create a markdown summary for a local research_ops iteration."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_manifest(iteration_dir: Path) -> dict[str, object]:
    manifest_path = iteration_dir / "iteration_manifest.json"
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def build_summary(iteration_dir: Path, manifest: dict[str, object]) -> str:
    required = manifest.get("required_artifacts", {})
    if not isinstance(required, dict):
        required = {}
    lines = [
        "# Iteration Summary",
        "",
        f"Iteration: `{manifest.get('iteration_id', iteration_dir.name)}`",
        f"Title: {manifest.get('title', '')}",
        f"Status: `{manifest.get('status', 'unknown')}`",
        f"Created: `{manifest.get('created_date', 'unknown')}`",
        f"Control: `{manifest.get('control_ref', 'unknown')}`",
        "",
        "## Artifact Status",
        "",
        "| Artifact | Complete | File exists |",
        "|---|---:|---:|",
    ]
    filenames = {
        "cartography_report": "cartography_report.md",
        "experiment_rfc": "experiment_rfc.md",
        "implementation_summary": "implementation_summary.md",
        "verifier_report": "verifier_report.md",
        "decision_memo": "decision_memo.md",
        "ceo_packet": "ceo_packet.md",
    }
    reports_dir = iteration_dir / "reports"
    for artifact_id, filename in filenames.items():
        complete = str(bool(required.get(artifact_id))).lower()
        exists = str((reports_dir / filename).exists()).lower()
        lines.append(f"| `{artifact_id}` | {complete} | {exists} |")
    lines.extend(["", "## Notes", "", "- Generated by `research_ops/scripts/summarize_iteration.py`."])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("iteration", help="iteration directory or iteration id")
    parser.add_argument("--root", default=None, help="repository root; defaults to cwd")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing reports/iteration_summary.md")
    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve() if args.root else Path.cwd().resolve()
    iteration = Path(args.iteration)
    if not iteration.is_absolute():
        direct = root / iteration
        by_id = root / "research_ops" / "iterations" / args.iteration
        iteration = direct if direct.exists() else by_id

    manifest = load_manifest(iteration)
    summary = build_summary(iteration, manifest)
    if args.stdout:
        print(summary, end="")
    else:
        path = iteration / "reports" / "iteration_summary.md"
        path.write_text(summary, encoding="utf-8")
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
