"""Generate the canonical screening / promotion doc block from code.

Avoids doc-rot: the sections between AUTOGEN:START and AUTOGEN:END markers in
v2/COMMANDS.md are regenerated from:
    - v2.core.walkforward.SCREENING_MODES
    - v2.core.artifact_kind.ArtifactKind
    - v2.core.cv_report.RESULTS_TSV_HEADER, SCHEMA_VERSION

Usage:
    python -m v2.ops.gen_docs --write    # rewrite the autogen blocks in place
    python -m v2.ops.gen_docs --check    # exit 1 if checked-in copy is stale

See /Users/gduby/.claude/plans/delightful-yawning-tiger.md Appendix H.
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
COMMANDS_MD = PROJECT_ROOT / "v2" / "COMMANDS.md"

BEGIN = "<!-- AUTOGEN:START harness_commands -->"
END = "<!-- AUTOGEN:END harness_commands -->"


def render_block() -> str:
    from v2.core.walkforward import SCREENING_MODES
    from v2.core.artifact_kind import ArtifactKind
    from v2.core.cv_report import RESULTS_TSV_HEADER, SCHEMA_VERSION

    lines: list[str] = []
    lines.append(BEGIN)
    lines.append("")
    lines.append("### CV pipeline (regenerated from code)")
    lines.append("")
    lines.append("**Screening modes** (see `v2.core.walkforward.SCREENING_MODES`):")
    lines.append("")
    for mode, desc in sorted(SCREENING_MODES.items()):
        lines.append(f"- `{mode}` — {desc}")
    lines.append("")
    lines.append("**Deploy commands:**")
    lines.append("")
    lines.append("- `./v2/ops/deploy.sh run_screen_latest exp_NNN` — fold 4 only, no artifact")
    lines.append("- `./v2/ops/deploy.sh run_screen_mini   exp_NNN` — folds 0, 2, 4, no artifact")
    lines.append("- `./v2/ops/deploy.sh run_cv            exp_NNN` — full 5-fold, emits CV_EVAL artifact")
    lines.append("- `./v2/ops/deploy.sh run_final_train  SRC_ID`   — train deployable model from chosen CV")
    lines.append("")
    lines.append("**Artifact kinds** (see `v2.core.artifact_kind.ArtifactKind`):")
    lines.append("")
    for kind in ArtifactKind:
        # The enum docstring is the comment line below the member; we fall back
        # to a simple description if no docstring is present.
        lines.append(f"- `{kind.value}` — "
                     + ("DEPLOYABLE" if kind == ArtifactKind.FINAL_TRAIN
                        else "not deployable"))
    lines.append("")
    lines.append("Only `final_train` artifacts are accepted by `model_manage keep`.")
    lines.append("")
    lines.append(f"**results.tsv schema** (`{SCHEMA_VERSION}`):")
    lines.append("")
    lines.append("| column | meaning |")
    lines.append("|---|---|")
    col_descriptions = {
        "experiment": "experiment id",
        "screening_mode": "full / latest / mini / legacy",
        "status": "revert (default) or keep (after model_manage.keep)",
        "stability_score": "mean fold score across evaluated folds",
        "pooled_pf": "pooled profit factor across all trades from all folds",
        "pooled_dd": "pooled max account drawdown",
        "pooled_trades": "pooled total trades",
        "pooled_traded_days": "pooled days with ≥1 trade",
        "any_gate_failure": "true if any fold gate-failed",
        "per_fold_scores": "list of fold scores",
        "description": "human-readable note",
    }
    for col in RESULTS_TSV_HEADER:
        lines.append(f"| `{col}` | {col_descriptions.get(col, '')} |")
    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def inject(doc: str, block: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        re.DOTALL,
    )
    if pattern.search(doc):
        return pattern.sub(block, doc)
    # Append to the end if markers are missing
    sep = "\n\n" if not doc.endswith("\n\n") else ""
    return doc + sep + "\n## Autogenerated harness reference\n\n" + block + "\n"


def main():
    p = argparse.ArgumentParser()
    group = p.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="Rewrite COMMANDS.md in place.")
    group.add_argument("--check", action="store_true", help="Exit 1 if checked-in copy is stale.")
    args = p.parse_args()

    block = render_block()
    current = COMMANDS_MD.read_text() if COMMANDS_MD.exists() else ""
    updated = inject(current, block)

    if args.write:
        COMMANDS_MD.write_text(updated)
        print(f"Rewrote {COMMANDS_MD}")
        return

    if args.check:
        if current != updated:
            diff = difflib.unified_diff(
                current.splitlines(), updated.splitlines(),
                fromfile="COMMANDS.md (checked-in)",
                tofile="COMMANDS.md (expected)",
                lineterm="",
            )
            print("\n".join(diff))
            print(f"\nERROR: {COMMANDS_MD} is stale. Run: python3 -m v2.ops.gen_docs --write",
                  file=sys.stderr)
            sys.exit(1)
        print(f"{COMMANDS_MD}: AUTOGEN block up to date.")


if __name__ == "__main__":
    main()
