"""Generate a private IBC config from macOS Keychain credentials."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import stat
import subprocess
import sys
from typing import Any


DEFAULT_USERNAME_SERVICE = "autoresearch-trading-ibkr-paper-username"
DEFAULT_PASSWORD_SERVICE = "autoresearch-trading-ibkr-paper-password"
DEFAULT_OUT = Path.home() / ".autoresearch-trading/ibc/runtime/ibc-paper.ini"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--username-service", default=DEFAULT_USERNAME_SERVICE)
    parser.add_argument("--password-service", default=DEFAULT_PASSWORD_SERVICE)
    parser.add_argument("--trading-mode", choices=("paper",), default="paper")
    parser.add_argument("--api-port", type=int, default=4002)
    parser.add_argument("--auto-restart-time", default="")
    parser.add_argument("--cold-restart-time", default="")
    parser.add_argument("--json", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    username = read_keychain_secret(args.username_service)
    password = read_keychain_secret(args.password_service)
    if not username or not password:
        payload = {
            "status": "missing_credentials",
            "out": str(args.out),
            "username_service": args.username_service,
            "password_service": args.password_service,
            "detail": "Run v4/ops/ibkr/store_ibkr_paper_credentials.sh locally; do not paste credentials into chat.",
        }
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 2

    args.out.parent.mkdir(parents=True, exist_ok=True)
    text = build_config(
        username=username,
        password=password,
        trading_mode=args.trading_mode,
        api_port=int(args.api_port),
        auto_restart_time=str(args.auto_restart_time),
        cold_restart_time=str(args.cold_restart_time),
    )
    args.out.write_text(text)
    os.chmod(args.out, stat.S_IRUSR | stat.S_IWUSR)
    payload = {
        "status": "written",
        "out": str(args.out),
        "mode": args.trading_mode,
        "api_port": int(args.api_port),
        "username_present": True,
        "password_present": True,
        "file_mode": oct(args.out.stat().st_mode & 0o777),
    }
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


def read_keychain_secret(service: str) -> str | None:
    result = subprocess.run(
        ["security", "find-generic-password", "-s", service, "-w"],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        return None
    value = result.stdout.rstrip("\n")
    return value or None


def build_config(
    *,
    username: str,
    password: str,
    trading_mode: str,
    api_port: int,
    auto_restart_time: str,
    cold_restart_time: str,
) -> str:
    lines = [
        "# Generated by v4/ops/ibkr/write_ibc_runtime_config.py",
        "# Contains credentials. Keep outside git and chmod 600.",
        "FIX=no",
        f"IbLoginId={escape_ini(username)}",
        f"IbPassword={escape_ini(password)}",
        "FIXLoginId=",
        "FIXPassword=",
        "SecondFactorDevice=",
        "ReloginAfterSecondFactorAuthenticationTimeout=yes",
        "SecondFactorAuthenticationExitInterval=60",
        "SecondFactorAuthenticationTimeout=180",
        f"TradingMode={trading_mode}",
        "AcceptNonBrokerageAccountWarning=yes",
        "LoginDialogDisplayTimeout=90",
        "IbDir=",
        "StoreSettingsOnServer=",
        "MinimizeMainWindow=no",
        "ExistingSessionDetectedAction=primary",
        f"OverrideTwsApiPort={int(api_port)}",
        "OverrideTwsMasterClientID=",
        "ReadOnlyLogin=no",
        "ReadOnlyApi=no",
        "AcceptIncomingConnectionAction=accept",
        "AllowBlindTrading=no",
        f"AutoRestartTime={auto_restart_time}",
        f"ColdRestartTime={cold_restart_time}",
        "ClosedownAt=",
        "SaveTwsSettingsAt=",
        "CommandPrompt=no",
        "SuppressInfoMessages=yes",
        "LogComponents=never",
        "LogToConsole=yes",
    ]
    return "\n".join(lines) + "\n"


def escape_ini(value: str) -> str:
    return value.replace("\n", "").replace("\r", "")


if __name__ == "__main__":
    raise SystemExit(main())
